stages:
  - test
  - build

variables:
  UV_VERSION: "0.10.9"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: trixie-slim
  UV_LINK_MODE: copy
  IMAGEN_NAME: seb4sbit/soporte_ti
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

.uv-install:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make
    - uv sync --locked --group dev
  after_script:
    - uv cache prune --ci

tests:
  extends: .uv-install
  stage: test
  script:
    - make test
  rules:
    - if: $CI_COMMIT_BRANCH == "feature/implementar-pipeline-de-ci-cd" # TODO: quitar antes de mezclar en main.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"

linting:
  extends: .uv-install
  stage: test
  script:
    - make lint
  rules:
    - if: $CI_COMMIT_BRANCH == "feature/implementar-pipeline-de-ci-cd" # TODO: quitar antes de mezclar en main.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"

build_image:
  stage: build
  image: docker:29.3.0-cli
  services:
    - docker:29.3.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build --build-arg MODEL_PATH=$MODEL_PATH -t $IMAGEN_NAME:$IMAGE_TAG .
    - docker push $IMAGEN_NAME:$IMAGE_TAG
  only:
  rules:
    - if: $CI_COMMIT_BRANCH == "feature/implementar-pipeline-de-ci-cd" # TODO: quitar antes de mezclar en main.
    - if: $CI_COMMIT_BRANCH == "main"
