# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: triage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'triage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctriage.proto\x12\ttriage.v1\"j\n\x13PredictImageRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x16\n\x0etop_k_override\x18\x04 \x01(\x05\"@\n\nPrediction\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x11\n\trouted_to\x18\x03 \x01(\t\"g\n\tModelInfo\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x16\n\x0emin_confidence\x18\x03 \x01(\x02\x12\x12\n\ndummy_mode\x18\x04 \x01(\x08\x12\r\n\x05ready\x18\x05 \x01(\x08\"g\n\x14PredictImageResponse\x12*\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x15.triage.v1.Prediction\x12#\n\x05model\x18\x02 \x01(\x0b\x32\x14.triage.v1.ModelInfo\"\x0f\n\rHealthRequest\"E\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12#\n\x05model\x18\x02 \x01(\x0b\x32\x14.triage.v1.ModelInfo2\x9f\x01\n\rTriageService\x12O\n\x0cPredictImage\x12\x1e.triage.v1.PredictImageRequest\x1a\x1f.triage.v1.PredictImageResponse\x12=\n\x06Health\x12\x18.triage.v1.HealthRequest\x1a\x19.triage.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIMAGEREQUEST']._serialized_start=27
  _globals['_PREDICTIMAGEREQUEST']._serialized_end=133
  _globals['_PREDICTION']._serialized_start=135
  _globals['_PREDICTION']._serialized_end=199
  _globals['_MODELINFO']._serialized_start=201
  _globals['_MODELINFO']._serialized_end=304
  _globals['_PREDICTIMAGERESPONSE']._serialized_start=306
  _globals['_PREDICTIMAGERESPONSE']._serialized_end=409
  _globals['_HEALTHREQUEST']._serialized_start=411
  _globals['_HEALTHREQUEST']._serialized_end=426
  _globals['_HEALTHRESPONSE']._serialized_start=428
  _globals['_HEALTHRESPONSE']._serialized_end=497
  _globals['_TRIAGESERVICE']._serialized_start=500
  _globals['_TRIAGESERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
