name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Instalar dependencias
        run: uv sync --locked

      - name: Lint (ruff)
        run: make lint

      - name: Tests (pytest)
        run: make test
